### ISSUE TITLE
望山战队7位成员，欢迎加持！

### ISSUE THREAD

**Issue by benew-2012** [benew-2012/BPupdate#2]
# 望山战队完成集结，感谢大家加持！

７位小伙伴按加入时间为序，排名不分先后

两周以来项目初步选人组队，完成组队，gogogo!

~~如果有在商业化方面，视频制作等技术方面特别出彩的同学，欢迎继续上船！~~

自7月9日开始,大家轮值当周队长，共同经历成长，共同成就优秀作业！

## 团队组成

|王路西  |（第一周当值队长）|　发起组队　文案牵头　统筹打杂 | 北京|
|----|----|----|----|
|燕传熙　|（第二周当值队长）|参与过程　用户研究　视频制作| 长春|
|Kevin旭偉　|（第三周当值队长）|参与过程　项目设计　差异化相关？ |  北京|
|phyllis|（第三周当值队长）|参与过程　资料战备　产品相关？| 南京|
|功夫熊猫|（第二周当值队长）|参与过程　设计和产品相关?| 北京|
|半个书生|（第一周当值队长）|参与过程　技术相关?| 长沙|
|子午鸟|观察员|观察指导　过程陪坑　| 北京|
|midori|守护者|项目智囊　素材支持| 北京|

### 六期新同学　王路西  
【名字】王路西   
【坐标】北京   
【职业】公共关系管理，品牌运营   
【爱好】读写，人物访谈   
【擅长领域】好像比较适合做运营，性格比较包容   
【学习感想／愿望】   
- 第４周入门，第5周开始明白点知识点   
- 作业再接再励，结业BP要尽力成为一个作品

### 六期新同学　燕传熙   
【名字】周海燕   
【坐标】长春   
【职业】教师   
【爱好】看各种类型的书，尤其是小说   
【擅长领域】高中教育、20个月以内的娃的养育   
【目前学习感想】   
- 认知写作学术语好多呀，我的语文是体育老师教的。   
- 继续写作，继续练习。

### 五期老司机　Kevin旭偉   
【名字】张旭伟   
【坐标】北京   
【职业】市场运营管理   
【爱好】运动健身，跑步，阅读   
【擅长领域】运营 
【目前学习感想】 
- 五期老学员，希望多和大家交流进步～

### 六期新同学　PhyllisShen   
【名字】沈园园   
【坐标】南京   
【职业】博物馆研究人员，中科院心理研究所在职研究生   
【爱好】博物馆教育、旅游、儿童发展心理学   
【擅长领域】国内外博物馆教育、演讲、讲解   
【目前学习感想】   
 - 认知写作课程信息量巨大，坚持最小行动。   
 - 改变习惯、刻意练习、与优秀的团队一起努力、分享、进步。

### 六期新同学　功夫熊猫
【名字】胡峰
【坐标】北京
【职业】区块链技术开发 项目管理
【爱好】阅读、跑步
【擅长领域】互金、区块链
【目前学习感想】
通过刻意练习，将知识内化为能力

### 六期新同学　半个书生
【昵称】半个书生
【名字】高龙
【坐标】长沙
【职业】学生
【爱好】读书，书法
【擅长领域】科普，计算机

## 战队游戏模式

- 本战队项目跟进节奏
   - 每天早中晚沟通各自想法
   - 固定会议室每晚７点到凌晨在线等你
   - 项目成员两两共舞，轮值周队，每周两位
   
   
### changelog
20180709 初创   
20180710  确认初步分工，修改
20180712  完成所有成员集结，结束招募

**Comment by ppho99** [comment]
六期新同学　功夫熊猫
【名字】胡峰
【坐标】北京
【职业】区块链技术开发 项目管理
【爱好】阅读、跑步
【擅长领域】互金、区块链
【目前学习感想】

通过刻意练习，将知识内化为能力

**Comment by benew-2012** [comment]
【昵称】半个书生
【名字】高龙
【坐标】长沙
【职业】学生
【爱好】读书，书法
【擅长领域】科普，计算机

战队集结完毕有这样牛逼的战队，那个弱不经风的我（虚拟队长）感觉充满正能量～

开船了！
