### ISSUE TITLE
【第一周望山最小故事】召唤你！

### ISSUE THREAD

**Issue by benew-2012** [benew-2012/BPupdate#3]
亲爱的小伙伴，还记得课程中学习过的“最小故事”知识点吗？

（王路西一时想不起细节，赶紧滚回去翻卡包～）

请运用最小故事来打开“望山”这个项目的愿景和期待～

## 最小故事

**望山这个项目，输出的是教育综合性服务，产品当然是老师，或是教学体系，或是独特的教具~**

## 最小行动

anyway,我们是望山的发起者，也是教育可供性的创造者。开动吧，最小行动写起来！！！

## 请你思考，把你的望山项目最小故事发到项目群或直接跟帖到仓库啦～

以下问题，帮助我们打开最小故事的思路，还可以再扩充发散：

- 故事主题是什么（自由吗，自由怎样和这个故事结合；创造吗？创造又怎样结合）

- 故事主线（故事主要矛盾是什么，人物冲突。。。。）

- 故事涉及知识点（怎样在文案，故事策划，BP设计，视频制作中运用知识点，埋在哪里，怎么埋）

- 故事解决教育什么问题（抓什么需求）

- 怎样解决（产品与服务）

本周将开启不定期快写，直到我们把最小故事打磨好！

## [望山项目有专用wiki]( https://github.com/benew-2012/BPupdate/wiki )

快来，把你的知识涉猎分享给他人吧，我们用可供性联接彼此。

**教育就是人生。BP就是一次自我教育的旅途！来更帖呀！！**

学习借鉴[老树新芽项目](https://github.com/Mina-yy/BPstory/issues/7)

**Comment by benew-2012** [comment]
初步是想了两条矛盾，没想好怎样取舍。

先按第一个矛盾【贫穷VS自由】来写最小故事：
    
## 初版
   -  刘望山大学毕业，婉拒实习单位万元工资待遇，回到望山村。
   - 望山村里全是老人和孩子，村里唯一的学校荒芜多年。孩子们滋事生非，盼不来老师。
   - 望山带回来四名志愿者，用项目制将家庭教育（德育）和社会教育（技艺），学校教育（知识）综合，并借助互联网为贫困县带来自由教育范式。
　　`被观察员同学打倒，说没有按最小故事，事件三反转事件一来写`
   
## 第二版
   - 望山村唯一的学校荒芜多年，盼不来老师。
   - 望山从望山村考到北京。 
   - 望山回来了。

## 第三版
　这一版感觉和另一个矛盾【创造VS从众 】更接近，是一个人选择建设性人生的苏醒过程。   
- 望山是个学生，在望山村刻苦学习。家徒四壁，走很远山路，梦想是走出大山（或成为改变乡村命运的人）   
- 望山大学毕业，在大城市就业结婚（走出大山但梦想被磨损）  
- 望山成为父亲，带孩子回到望山生活（成为孩子们的老师，寻找人生价值）

**Comment by VickyZhouCC** [comment]
【180710】第一次团队线上快写~燕传煕

# 望山计划 最小故事

故事一：刘望山挥手告别村口的大树，大树的叶子哗啦哗啦响，沿着石头搭成的深黑浅黑弯弯曲曲的小路，走向山下，身后是深绿浅绿的各种植物，身前是城市明亮的灯光。刘望山深深吐出一口气，终于考出大山了！

故事二：公交车上拥挤的人群中紧皱的眉头、困在写字楼里灰色的办公桌和白色的墙壁中紧抿的嘴和眼中的光、酒会后撕心裂肺地呕吐、身边突然闪现新闻播报：“望山村最后一位老师刘树在雨中送孩子过河回家，被大水冲走”。
刘望山突然紧紧捂住了脸：“老师——”
脑海里闪现刘树老师的笑脸：“望山，你回来了？”
望山站在自己公寓的门口深深地犹豫——
门口的大树一再出现在他的梦里，望山从犹豫到坚定，他想回家，他想为家乡做点什么。

故事三：刘望山和被他心意感动的四个年轻人搭乘着面包车，又一次踏上了弯弯曲曲的石头小路。顺着缆车过了大河，站到村口大树旁。望山抚摸着粗大的树干：“我回来了——”

# Changelog

第一版
自评：只有故事梗概。
四个年轻人出现突兀。可以改成刘望山自己回家，然后把自己的生活拍成视频，感动了天南海北的四个年轻人，他们也来到了望山村。

**Comment by PhyllisShen** [comment]
第一次团队线上快写~PhyllisShen

# 望山计划 最小故事

场景一：“在那遥远的西南边疆，有一个叫做望山的地方。那里明月低缓，清风吟唱。可是那里也贫困荒凉，孩子们上不起学、没有崭新的衣裳，只能站在巷口张望。”画外音

场景二：第一次走进它，山里细雨朦胧，掩饰着昔日的小径；山野连绵，重复着昨天的内涵：青山绿水，鸟语花香。敲开几户人家，大多是老人和成群的孩子。近年来，随着农村生产力的提高和打工潮的出现，为了生计，为了翻新住房，为了积攒孩子以后的婚礼嫁妆，大量农村剩余青壮年劳动力纷纷涌向城市，把孩子留给他们的父母。这些老人对小孩的态度是“只管他们穿衣、吃饭，至于学习，那就管不了那么多了”。

场景三：上课了，“教室”里的孩子们是那样的专注，丝毫没有因为站着上课而感到辛苦，也许是书中的知识让他们暂时忘记了疲劳，也许是他们早已习惯了这样的学习方式。
旁边的房子是教室吗?那黑乎乎的没有玻璃的窗户，不见有一丝光线透出;那厚厚的土墙，也许年代久远，也许已步入危房行列。
孩子们手上的书本都已卷了边，依稀可看清“语文”二字，是上届的哥哥姐姐们留下的还是山外好心人士捐助的已不得而知，但它却让孩子们爱不释手;孩子们是那样的虔诚，那样的投入，捧着书本，朗朗书声似乎已跃然纸上。
孩子们手上拎着的，是火盆吗?在脚踩泥地头顶青天的“教室”里上课，天寒地冻之时，火盆对于食不果腹、衣不蔽体的孩子们而言，可能是唯一能给他们增加热量带来力量的“奢侈品”了。小女孩虽然已有些不堪重负了，但她依然舍不得放下，让火盆靠自己的身体近一些，再近一些，那样，温暖就多一些，哪怕多一丁点也好。
没有统一的制式校服，没有课桌，没有椅子，孩子们蓬乱的头发，不太干净的衣服，手上吊着的“书包”，还有脚上的泥鞋都在诉说着孩子们的艰辛与不易，可这一切丝毫没有减少孩子们的学习热情。
看着他们心中祈祷“但愿今天的书声能换来孩子们明天的幸福。”

***
## Changelog
    2018/7/10

第一版
自评：完整故事的脉络还没有想清楚，顺着小伙伴们的思路快写了三个场景。

**Comment by benew-2012** [comment]
第一次团队线上快写~王路西

**望山最小故事**
周末看了纪录片[《大迁徙》]( http://www.iqiyi.com/a_19rrh9qrz9.html?vfm=2008_aldbd )，看到所有物种几乎都会为了生存或下一代迁徙的规律。推荐看，叙述文采和故事，逻辑都很赞！
想把望山的群体故事，放到自然界进化里来，为下一代辛苦迁徙，撕杀（人类现实就是这样）
比如鲑鱼，牛羚都是不会迷路的，世世代代迁徙路线都是遗传着进化。(隐喻教育是基因进化)
但没想好和故事的结合方式，尤其是视觉上怎样展现。

# 回到望山

## 奋马扬蹄（自由第二阶段）

车子盘过一座山又一座山，穿过一排树林又一排树林。近山的山路挨着被开荒的山体，不成规则的堆砌着原始的崖石，雷雨时被震塌的巨石还躺在路边，没人搭理。漫山葱郁林子里偶尔跑出只野兔，抬头看来人一眼便自顾自的找食儿去。一切天然得令人不舍。

云南这个地方奇怪得很，火车开得比汽车慢。自从镇毕高速6月份通车，望山像奔赴恋人约会一样，索性开车回来了。他一路开得不算慢，但到眼下他开得更灵活了。眼睛紧紧盯着蜿蜒的山路，方向盘抓得牢牢的。８月毒辣的太阳罩在头上晒得人两眼发花，但他小心着呢，他太熟悉盘山公路下陡峭悬崖，他不想命丧黄泉。

从这辆不算新的北京吉普后视镜看过去，妻子云素一脸疲惫，３岁的儿子星星枕着妈妈腿，脑袋下面留着一潭口水，想是正在做着什么美梦。`这里　倒叙　场景先行　事件三望山带着妻儿回村`

望山不禁内心感慨：自己像星星这么大的时候，可没有美梦可以做。。。。。。。。。　想起二十年前的自己，想起二十年前的云蒙山区镇雄镇望山村，望山的心像打翻了的西红柿鸡蛋汤，红一块白一块，说不上是怨也说不上是爱。。。。。。。为了脱贫村里的中青少三代基本都外出务工，邻近四个村全是留守老人和留守儿童，望山就是其中一个。

## 安贫守道（自由第一阶段）

那破败的教室，只有十来平米，周边三四个村的孩子每天聚在这里，听周老师讲诗经讲书法，望山每次讲到[关关雎鸠，在河之洲，窈窕淑女，君子好逑]，９岁的望山总会被这朦胧的诗意感动，傻笑被周老师骂。。。。。。。周老师实在是太老了，76岁教到79岁，终于有一天教不动归天了。从此，望山村再没有老师来。山路上茅草一脚深一脚浅的长着，自生自灭。`那里　事件一望山幼年上学很难`

这一天，望山毕业了。毕业典礼之后的一天，他特意去北师大南门外。。。。。。新街口依然人来人往，从此却少了他这个从大山里走出来的孩子。宿舍里最后一晚兄弟们睡不着，借着酒精的挥发大家聊了一晚上人生梦想。望山的梦想一直没变，那是他10岁时就立下的志向：走出望山村，再也不回来。   
`这里　事件一望山立志要走出望山村｀

望山成了这家C轮几千万美金融资的在线教育公司XXX的教研团队成员，这是一家以拍照搜题APP为初创业务的明星企业，创始团队均来自杜克耶鲁，是国内精英教育的样板。。。。。。。。。   
`那里　事件二望山在大城市就业结婚`

## 当世取舍（自由第三阶段）

三年后，望山结婚了。再两年，望山有了儿子星星。。。。。。。。教育，自由，创造，价值，当这些毫无关联的问题一起涌向他的时候，望山突然间开悟了。。。。。。。

他要一路向南，回到望山。`这里`

“我们在感谢刘望山同志，是他为我们望山村带来了新教育，新自由，新未来”村长老姚头站在台前，笑容可掬。今年他的孙子，和村里其他８个孩子一起考上了云南大学，武汉大学。这在过去想都不敢想，现在周边三四个村子，可全都出过大学生了。望山坐在台下，从没有这样感觉过自在。｀那里｀

[求之不得，寤寐思服。悠哉悠哉。辗转反侧。]想想这几年，自己为了搞这个“组织型教学法”实验，受过多少白眼挨过多少批评花费多少心血。。。。。。他当年带回来四个志愿者可都是本村的孩子，他们一起按科学的方法，把家庭教育，社会教育和学校教育的目标融合在每天24小时的陪伴中，让附近村的孩子们混龄学习，亲身实践，光是培养老师就孵化了近三年。。。。。

一切天然得令人不舍。望山比谁都明白，这里，才是教育最自由的阵地，才是把美德，财富和知识揉搓出美丽线条的地方。远处苍茫云海间，明月出天山。`首尾呼应　比喻　`

## 自评
1. 　只结合场景，隐喻自由和隐喻教育并没有体现
2.　未找到文化习俗结合，比较硬
3.　快写没有组块，写出来再组块

## Changelog
- 20180710  初稿　1H
