### ISSUE TITLE
参考素材库

### ISSUE THREAD

**Issue by PhyllisShen** [benew-2012/BPupdate#5]
**思考：一句话定义【望山项目】是什么？**

## 我参与望山项目的目的

真正让公益对象受益的项目，“授之以鱼不如授之以渔”。如果我们想做好公益项目，就需要建立思想的平台。没有施舍与被施舍，只有思想交流，彼此尊重。

**公益公益——天下为公，人人受益。**

我们核心产品（望山项目）价值是解决一个什么问题？我们的最小故事故事性不够强，没有冲突逆转。联系认知写作课上三个故事的关系是否可以梳理成：有什么（乡村现状），要什么（望山项目），怎么做（志愿者实施）；或者要什么（孩子理想的成长环境），有什么（乡村现状），怎么做（望山项目）。

## 我的疑问：

1、望山项目最打动人的地方是什么？

2、望山项目BP的目的是倡导公益？志愿服务市场化？招募志愿者？推介项目？呼吁重视家庭教育？

****

以上问题欢迎大家讨论留言！开这个issue的目的是把组队成功后的第一次资料收集放进来，大家以后看到好素材一并粘贴在下面。我先抛砖引玉~~~

**Comment by PhyllisShen** [comment]
8分钟动画零台词却获117项提名64项大奖：[你剪断了我的翅膀，却怪我不会飞翔](https://mp.weixin.qq.com/s?__biz=MjM5NTMzMjE2OQ==&mid=2652054709&idx=1&sn=9965e7aa81a03269a908d735c0a01cd3&chksm=bd1dad938a6a248544faaa249a5c1221ca3a8e8cbd62901b5c3afb0625c1b1f37a304cbf9327&mpshare=1&scene=1&srcid=0502L2DhKryG1qDQokXLZI3j#rd)

**Comment by PhyllisShen** [comment]
[望山项目参考素材库1](https://github.com/PhyllisShen/database)

@PhyllisShen 

文件格式后缀是.caj，好像打不开，换成.md格式呢？

或者直接用　[ ](超链)　格式，不用下载呢。

**Comment by benew-2012** [comment]
乡村留守儿童创新服务案例

纪录片：[180台DV的故事]( http://www.doc88.com/p-7008970073045.html )

论据：[乡村生活，激发孩子探索欲望]( http://www.doc88.com/p-3127588482762.html )
`假设城市孩子家庭寒暑假去乡村小孩家里游学`是有探索条件，动机和课程设计可能，需求的。

**Comment by benew-2012** [comment]
@PhyllisShen 　

辛苦找了好多资料呀，干粮有好几百个！

反馈如下：

文档是　.caj　后缀，貌似打不开，要不换成　.md　后缀？
如果工作量太大，可以把素材按类找，格式上看有没更简明浏览方式，不要累坏啦（抱）

8分钟动画零台词，感动死人啦～

灰色的人生和鲜活的人生，隐喻在音乐，色彩，情节，表情上结合得都非常棒。

第一个帖子建议搬到[项目方向和诉求主题讨论 ]( https://github.com/benew-2012/BPupdate/issues/4 )深度垂直交流做什么，此主题讨论请大家都发到那里。

这里既是参考素材库，就全部发素材，这样资料多了，好按标题快速进入话题。

以上供参考。

**Comment by benew-2012** [comment]
[ 农村留守儿童问题](http://www.baywatch.cn/jiaoyulunwen/liushouertonglunwen/102665.html)

>根据研究表明：“少年儿童身心发展处于容易变化的转折期，其心理和生理成长发育尚未成熟，可塑性大，自制力不强，这阶段的‘留守儿童’一旦脱离家长的管教与科学引导，很难抵制不良诱惑，很多留守儿童由于无人管教或管教不当而与社会上的不法分子混在一起，养成了不良的行为习惯。”而在生活中，留守儿童良好的饮食和卫生习惯也没有完全形成，他们生活经常没有规律。

>留守儿童性格形成的关键时期是小学，而他们的监护人———爷爷奶奶非常溺爱他们，造成了他们的任性和叛逆；再加上孩子跟随老人一起生活，在反应力、思想行为方面相对其他孩子要缓慢一些，这也造成了日后和他人交往、交流产生一定的障碍。现在我乡村大部分的“留守儿童”教育，以隔代教育和寄养教育为主，遇到心理问题得不到及时疏导，遇到不当行为的表现得不到有效制止和教育，极大地影响了他们心理和生理健康发展，导致不少“留守儿童”自卑自闭、寂寞空虚、软弱无助及逆反心理严重。生活中，难于沟通，爱发脾气，常与家人及老师产生隔阂，这些对于留守儿童的成长非常不利。对于留守儿童自主阅读习惯更为不利。

>培养学生兴趣，可按照年级由浅入深进行。培养学生动口、动手、动脑、动笔习惯。重点培养孩子们的阅读兴趣，主要按年级指导。

（１）一年级主要以图画为主，指导其如何看懂图画书；并能用简单的语言描述图画上的大致内容。让孩子从小养成看课外书的良好习惯。

（２）二年级主要以图文为主，指导其借助拼音读懂图画书的内容；并能试着口述每个图画的内容，或用简短的话来说说自己的感受。

（３）三四年级以故事书、幽默大王为主；同过教师指导孩子能读懂故事内容，并能用自己的话来描述故事内容。

（４）五六年级以一些成长故事书或带有启迪性的故事书为主，通过指导，能看懂故事内容，并能动手摘抄一些好词、佳句和描写优美的段落。还能通过故事内容写一些阅读后的感受和评价。

**Comment by PhyllisShen** [comment]
亲爱的路西，没能及时的反馈你的建议，非常抱歉。素材方面我来更换一下格式上传，方便大家查找。
