### ISSUE TITLE
邀你进入童年时光机——故事文案

### ISSUE THREAD

**Issue by benew-2012** [benew-2012/BPupdate#7]
教练上次点评时，推荐我们看看几米的[《月亮忘记了》](https://github.com/benew-2012/BPupdate/wiki/%E7%81%B5%E6%84%9F%E8%A7%A6%E5%8F%91%E5%99%A8%E2%80%94%E2%80%94%E5%87%A0%E7%B1%B3%E3%80%8A%E6%9C%88%E4%BA%AE%E5%BF%98%E8%AE%B0%E4%BA%86%E3%80%8B)

## 栗子：绘本故事［美丽的地球］

文／图　[日] 刀根里衣

孩子们经常听大人谈论可持续发展，气候变暖，温室气体等。在这个故事里，84只企鹅象征的是率先签订《京都议定书》的84个国家和地区。《京都议定书》于1997年签署，目标是减少工业化国家的温室气体排放量。温室气体是全球变暖的罪魁祸首，而全球变暖对环境有着巨大的影响，甚至会威胁到某些国家的生存。

减少温室气体排放量，每个人都可以贡献自己的力量。积水成渊。照料地球，就是照顾好我们共同的家园。

## 故事开篇(空间先行)：
大浮冰融化了，84只企鹅不得不另寻新家。
可是，它们能去哪儿呢？
地球已经被污染得如此严重......

## 故事文案

地球变暖，浮冰开始融化。
有84个家庭成员的企鹅一家，决定要搬家了。

——应该会有更美好的家园吧？
让我们乘着冰船去寻找吧！

——我听说，南方有一片特别美丽的海洋。（这里）
——真的吗？一个海底的家，该多美啊！

——哎呀.....水可真脏！
——这里根本不能住！

——我听说，东方有一片特别辽阔的草原。（那里）
——在那里，我们可以在柔软的青草上安睡......
现在就出发吧！

——哎呀.....这里只有工厂！到处都乌烟瘴气的.......
——这里根本不能住！

——我听说，西方有一片开满鲜花的山岗。（这里）
——那里一定弥漫着花香......
还有很多蜂蜜！

——哎呀。。。。花儿呢？只剩下枯死的植物.....
——这里根本不能住！

——我听说，北方有一片风光壮丽的森林。（那里）
——在树上生活......听起来真诱人！
这一次终于能找到我们的新家了吧！

——.......?!

——地球上没有可以住的地方了......
只能去更遥远的地方了吗？

——咦，你们看，
从这里望过去，地球如此美丽......

——还是回去吧！
我们现在知道该做什么了！

——好好照料我们的地球。
——大家齐心协力，一定能让它康复！

## 分析：故事策略

- 主题：环保
- 隐喻：
  - 84只企鹅－84个国家和地区
   - 动物迁徙－企鹅搬家
  - 南方－海洋
  - 东方－草原叼
  - 西方－山岗
  - 北方——森林
  - 气候变暧－红色的企鹅（画面）
  - 浮冰——乘着冰船（画面）
  
- 主线：企鹅寻找新家
- 隐线：爱护环境，人人有责（集体潜意识）
- 情绪冲突：
  - 主要任务：找到适宜生存的新家
  - 目标＆对抗因素：坚信的美好 V 实际的毁灭
  - 想安居——浮冰融化——被迫要搬家
  - 希望去南东西北——失望没法居住
  - 决定搬家——重拾信心回到原地
  
 - 最小故事
   - 事件一：84只企鹅（因环境恶化）决定搬家。（状态）
   - 事件二：他们乘船去寻找新的家园。（行为）
   - 转折：去了地球的东南西北，污染严重。(空间变形)
   - 事件三：回到原地，照料康复生存环境。（转折）

- 用九句话描述故事
- 故事树生长方向：属于第三人称限制叙述吧
 
 | 悬念 |1 | 气候变暖，浮冰融化。 | 
  |---- |---- | ----|
 | 第一部分说明（布局） | 2 |红色的84只企鹅出场 | 
   | 第一个情节点|3 |企鹅们决定搬家|
 | 第二部分说明（反应，旅程开始） |4 |乘冰船开始寻找|
  | 中间点|5|去记忆中南方美丽海洋，水很脏|
   | 第三部分说明（主人公变得更积极主动） |6 |去东方草原，乌烟瘴气，去西方山岗枯死的植物，去北方森林，无法居住|
   | 第二情节点|７|企鹅们决定还是回去|
   | 第四部分说明（主人公成为....催化剂） |８|企鹅反省要好好照料生存环境|
   | 结尾或问题得以解决|９|齐心协力，让地球得以康复美丽

**Comment by benew-2012** [comment]
童年时光机第一版文案－王路西
---
## 项目一：童年时光机
### 项目特点：可能会胜在故事（人性对爱和守护刚需，孩子作品美），问题是家长信任（可行性）。
###  产品机会
商业方向：青少年同龄陪伴
目标人群：城市和乡村家长
使用人群：7-15岁儿童端／家长端
核心诉求：父母不能陪伴，老人照看，孩子孤僻
典型场景：一个城市孩子听三线城市孩子讲当地风俗文化
产品与服务：童年时光机－同龄限时陪伴APP 
商业案例：摩尔庄园（社交＋游戏）（这里是艺术兴趣分享＋生活方式社交））

## 最小故事

BP逻辑呈现结构：
１，用童年时光机后，孩子更主动关心家人，作业配合度更高，还发展兴趣
２，回顾之前的阴暗无陪伴的经历，用日记体呈现孩子从封闭到开放内心变化　
３，挖掘为什么会产生变化，他在童年时光机有一个朋友每天陪伴他一小时
４，呈现产品价值和功能，妈妈理解了陪伴的意义

## 故事文案
**打开童年时光机** 
　　每天陪伴比一次拥抱更温暖

（场景：周末一天。）

今天是2018年7月12日，
早上７点陪老妈楼下遛狗，
８点吃五包子一苹果，
９点开始做作业，
数学和语文一小时全解决，
还玩了会儿编程游戏。
　　　——皓然日记

昨天是奶奶生日，
我攒了零花钱，
帮奶奶挑了款好看的墨镜，
我奶年轻时像个大明星，
我妈说她如今是美人迟暮。
　　　　——皓然日记


对，你们只认识现在快乐的我，
不曾了解我过去趟过的小河。
快乐总是短暂，
小学后妈妈完全不属于我
........

翻到这里，妈妈的手指僵住了。
半年之前的皓然还是逆反少年。
看这稚嫩笔触下的幽怨，
冷，像一点点积攒下来的雪花。
妈妈眼睛模糊了，
心里被惊讶和委屈填满。

（ 场景：一家儿童医院的病床前）

瑶瑶，你寄给我的香水百合刚收到。
医生正在查床，我的腿已经消肿。
趁着百合还有鲜活的味道，
我写一首诗给你：
百合
百合的花蕊是白色的，
我的生命是五彩的，
捎一只芬芳的热汽球，
为我带去热烈，
谢谢你，陪我半年的朋友。
　　　　——皓然日记

（场景：一个县城郊的公园里）
一个女孩正拿着画板写生，
她先画了一池荷花，
又小心翼翼在旁边签上一个名字“瑶瑶”。
她要把这张画送给远在北京的皓然，
希望他每天再开心一些。

（场景：家里，妈妈陪着皓然打开童年时光机APP）
我挑这一天，和视频里面的瑶瑶，
一起过10岁生日，一起吃蛋糕唱生日歌。
谢谢童年时光机，
谢谢在这里遇见每天的你，
现在，我重新找到陪伴乐趣。

借助童年时光机，在这里找到想要的同龄小朋友，
为你写诗，读书，朗读经典
和我画画，拍照，录视频
一起过生日，探索知识，聊聊兴趣

只要每天一小时同伴高质陪伴
借助艺术和行为，激活心理需求和情感认同
陪伴孩子，唤醒童心内生力

（场景：呈现小时候有人陪的感觉）
小时候，
妈妈抱着襁褓中的我，
“看见那朵墙上的花草，她就会笑”

幼儿园第一天，
妈妈穿着套裙和我在校门口留念，
“第一天上学，要开心点哦”

小学毕业那天，
和一帮同学必胜客聚会，
“皓然来把你做的披萨分给小伙伴”


（最后展示下感知力强的孩子的可供性）
　　主动关心他人，靠行为获得同辈认可
　　专注兴趣爱好，引导自我找到人格方向
　　善于倾听他人，也会移情和内省
　　　想象力丰富，也能快速解决问题
　　　饱满的安全感，自我就是连接自我与世界的可供性
　　　
一次拥抱不如每天陪伴
　用“童年时光机APP”
只要每天一小时高质同伴陪伴
　来吧，和我牵手去兴趣小镇，记录我们的成长蜕变。

**Comment by PhyllisShen** [comment]
几乎所有令我们成人头疼的儿童问题，比如暴力、高需求粘人、沉溺游戏等等，最终都能找到一个相同的源头：父母陪伴的缺失。
科学家做了一项研究发现，根据“陪伴”的定义，有的孩子平均一天只能从父亲那得到7分钟的陪伴，从母亲那得到11分钟的陪伴，而更可怕的是，被调查的很多父母都还一直以为自己已经花了很多时间陪着孩子了。
**这是第一个让我反思的重点，陪着和陪伴是两回事。**

很多父母定义的“陪伴”就是出现，我人在那了。这也常常是不少父母的呐喊：我下班回家后就一直陪着你，你还想让我怎样？！于是，不少家庭就进入了这样一个恶性循环：孩子大哭大闹非常粘人，父母心力交瘁还要强打精神陪着；孩子反而更加粘人，父母绝望。
导师说，这样的例子特别特别多，这也是她在做咨询时很多为人父母感到委屈的地方。但后来通过她的跟踪观察，她发现，大部分的家长普遍都是肉身在，但头脑和心都是冰冷的（Warm body but cold head and heart）。
极其粘人难带的孩子，父母想着的就是赶紧解决问题，于是按压着内心的烦躁在陪着；即使不是那么难带的孩子，在如今忙碌和被高科技充斥的社会，我们太容易被分心了，陪着孩子心里却想着明早开会和老板要讨论的话题、今天晚饭做什么、在关心是否可以拍到足够可爱的宝宝照片发朋友圈，或者甚至直接就是埋头看手机刷朋友圈。

孩子的心特别纯净，因此也特别敏感，他们是最能感知我们是不是真心的。 那些“假装在陪伴”其实比缺席更严重，因为我们的行为在告诉孩子，即使我们在一起，你太无关紧要了，以至于我可以分心去考虑其他事情。于是，缺少关注和爱的孩子，就会从其他途径来寻求关注。而大部分孩子就会发现，只有当她大哭大叫，调皮捣蛋时，父母才会真正全心全意开始陪伴，而不是陪着。这也就成了很多孩子索取爱和关注的途径了。
是的，为人父母就是一件很麻烦的事，但如果这件事我们不得不做，那不妨在做的时候更走心一点。用心陪伴其实并没有我们想象的那么难，最关键的是，我们真的愿意花时间，这是一个态度上的转变。

导师给了五个一的建议：
每天至少一次完全没有手机干扰的陪伴；
每天至少一次和孩子一起疯狂傻笑；
每天至少一次身体接触（拥抱、亲吻等）；
每天至少一次放下“教”孩子的念头，而是跟随孩子玩；
每天至少一次看着孩子的眼睛说，我爱你，我喜欢和你在一起！

而在陪伴的过程中，父亲和母亲的角色同样重要。男孩从父亲那里学会如何成为一个男人，女孩通过对父亲的欣赏、爱戴和信任学会今后如何和其他异性相处，而这些一定需要父亲花时间和孩子互动，这些是电视、玩具等无法替代的。

孩子从母亲那里学会如何爱、照顾和信任，从小得到母亲更多关注的孩子，会有更强的自尊水平，从而有更好的和他人互动的能力。而这些不仅需要母亲花时间和孩子互动，更需要母亲本人有一个比较稳定的情绪状态。

**这就是我反思的第二个点，关于用心陪伴的定义中，对于父母亲的侧重点会有所不同。对于父亲来说，孩子需要的是真正不分心的“花时间”陪伴；而对于母亲来说，是愉快不焦虑地用心陪伴。**

一个孩子从出生到上大学之间，我们和孩子共同拥有的只是940个周末。那以后，你再盼着孩子缠着你、再盼着孩子和你说话也许机会都会很少了。

请珍惜现在每一天，每一个个周末，和孩子创造欢笑的回忆，而不仅仅只是给孩子花钱！

**Comment by benew-2012** [comment]
@PhyllisShen  赞成对“陪伴质量和陪伴效果”的重视，我们可以试着在Bp中呈现这组矛盾。

`《童年时光机》项目BP迭代记录：`

[BP第一版]()

[BP第二版]()

[BP第三版](https://github.com/benew-2012/BPupdate/issues/7)

## 《童年时光机》第四版BP故事和文案

>故事必须用最精炼而又完整的话语表述。——伊丹万作

受《复眼的影像》建议，重新考虑我们故事的主题。思考如下：

- 故事主题：一句话讲清楚故事是什么？
一个人因为濒临孤独，找到了另一个人。（主题就是讲孤独，普世的孤独，孩子只是特定人设）

- 开场，故事人物设定：
## 1.妈妈（大人的孤独人设）
职业：互联网创业公司成员（忙，没时间照顾家人和家庭，被离异）
生活场景：公司各种会议，晚归，周末家里的移动办公人士
行为特点：自以为是，不安全感，逞强，吹毛求疵，手机不离眼
情感诉求：付出被认可，努力被尊重，安全感，占有欲
背景设定：自由恋爱结婚，老公外遇离婚，要强
开场视角：回忆一家三口周末幸福时光


## 2.城市孩子A　陆皓然（小孩的孤独人设）
职业：学生（小学四年级学生，作业繁重，奶奶接送，父母陪伴少）
生活场景：学校里苦闷，老师眼中很一般的学生，家庭冷寂
行为特点：厌烦作业，孤僻叛逆，在家喜欢写日记
情感诉求：渴望被重视，被理解，被信任，敏感
背景设定：探索欲望强烈，有细腻敏感的触角
结尾视角：和妈妈一起去了趟乡村


## 3.乡村孩子B　万薇薇（孤独人设）
职业：学生（小学五年级学生，留守儿童，父母陪伴少）
生活场景：学校和家之间两点一线，生活场景丰富
行为特点：懂得给予，早熟，喜欢在野外画画
情感诉求：孤单，热情，乐观
背景设定：常年和爷爷一起生活，父母外出
开场视角：10岁生日收到一个手机


## 4.故事情节变复杂
A父母离异
妈妈被老师谈话
收到一个陌生来信

> 永远别忘了每个人物的特定年纪和经历。找到每个人物的核心情感。将对白A-B化。——《你的剧本逊毙了！》

## 5.最小故事

### 事件1：

周末，客厅的时钟刚刚指向上午10点，阳光斜斜的落地窗台上,栀子花零零碎碎的撑着白色的脸盘，微风中似还有暗香。妈妈枯坐一隅，心不在焉地翻看着手机。屏幕画面定格在三年前，皓然和爸爸在地板上一起玩游戏，她在沙发上静静的看书，桌上的栀子散发着幽香，夏风席席，岁月静好。而现在先生走了，家空了，生活变味了。

不远处，皓然正在用小手给80岁的奶奶捶背，奶奶常年坐股神经痛。电视里小声的放着动画片，皓然扭头深深地看一眼妈妈，捶背的手停在空中，10岁的他低头和奶奶轻轻耳语一声，走到厨房给妈妈泡了杯她喜欢的茉莉花茶。

“妈，我好喜欢你身上淡淡的茉莉香，想尝尝吗？”。

那个心思低落的妈妈抬起头，看着儿子明朗的笑和伸过来的稚嫩双手，眼睛里有流动的波。拼命加班努力奋斗，到头来还是儿子温暖，她伸手接住，心里愧疚。


### 事件2: 

假如三年前妈妈没有加入那家互联网公司，假如不是每天加班到凌晨，连周末也要抱着笔记本开工作会议.......假如能多陪家人聊聊天，吃全家餐，给家人更多看得见的爱，爸爸该不会和妈妈离婚吧？

那时皓然才升二年级，爸爸刚升职，妈妈刚刚干得有起色。在家里，爸爸和妈妈似乎是一个虚拟存在，早上上学晚睡还没起，晚上睡前他们还没下班回家。每天陪伴皓然的，只有奶奶。每天总是玩玩牌，写写作业，看看电视。周而复始。

直到妈妈被通知到学校开家长会，才知道皓然在班里注意力不集中，小朋友社交关系紧张，各科进度跟不上。

老师问：最近皓然自信心不足，你有观察到吗？妈妈不置可否。
老师又说：孩子性格有些漠然，和刚来学校时的活泼积极有明显差别。尤其上台特怂。

自那以后，妈妈注意到皓然每天都会写日记。她自己也有写字看书画画的习惯，尤其是一个人毫无生气时，这是个养心的好习惯。

直到上个周末打扫房间时，皓然的桌子上躺着一封信，信来自云南腾冲，歪歪扭扭的署名“万薇薇”，乍看像山野里一朵孤零零的小花。妈妈没当面问皓然，只等着他来主动讲。

### 事件３：

“妈，我想把这部旧手机送给一个好朋友。”皓然生日这天，收到爸爸快递给他的一部新手机，原来的旧手机也还能用。他想起瑶瑶上次写信说，自己10岁生日时希望能有一部手机，可以和爸爸妈妈联系，也可以和皓然联系。

妈妈当然是同意的，还专门陪他去邮局寄给了远在云南腾冲的“万薇薇”。她和儿子一样，开始关心并感谢这个千里之外的“儿子的朋友”：春天开满桃花梨花油菜花紫云英的小山，一山又一山。夏天澄澈的天空，满天星斗像能摘下来似的。秋天开在山腰子上的桂花，该是五里地外都香遍了吧。还有冬天瀑布上结的冰晶，一簇簇的气腾腾的温泉。那是“儿子的朋友”画的画，好一个清净自在而又缤纷有致的地世界。

万薇薇是一个公益机构的公益扶持对象，起初是在一款“童年时光机”公众号上画画，陆皓然是她的粉丝，后来参加公众号上一个“找童伴”的交换游戏时，有了薇薇的通讯地址。薇薇开始每月给他寄自己的画作，直到寄了两个月，皓然才开始提笔回第一封信，那时候爸爸和妈妈刚离婚，家里氛围压抑，妈妈脾气暴烈，皓然在学习上和情感上承受巨大压力。但真正的给予不求回报，薇薇的画和她的故事感动了她，慢慢的他开始给她写诗，心中的烦恼开始有了宣泄的出口。

随着两个好朋友交往的加深，皓然知道薇薇生活在乡村，常年由爷爷照看，父母外出工作，一年也难见一面。那里只有一所九年义务教育学校，薇薇的所有娱乐就是放羊，看星空，画画，帮大人种收庄稼。可她的画是那样饱满生活的热情，面对人生的孤独，比自己坚强勇敢得多。

三年前，正是“童年时光”交换带来的生机，通过每天一小时“童年时光机”高质陪伴，将皓然从老师眼中“孤僻孩子”变回阳光小少年。今年收到手机，她们可以从写信画画的漫长等待到实时手机拍照片，写诗到读诗，拍视频，做一个真正的时间尽头的朋友。

随着状态改变今年期末，皓然各科得到优异成绩。暑假，妈妈准备带皓然去云南腾冲，去看看“薇薇”和她画里的世界。“真正的给予不求回报”，这也是皓然和薇薇告诉妈妈的道理，像孩子一样对生活投入不求回报的热忱，才是生命活过的真义。爱，像重新回来了。
